### ISSUE TITLE
No license :(

### ISSUE THREAD

**Issue by moqmar** [vitalibo/bitbake-intellij-plugin#3]
I think this plugin deserves a lot more attention and would benefit from regular updates and being published on the JetBrains Marketplace. I would gladly help maintain, publish and update it, but unfortunately there doesn't seem to be any license, so it can only be really used within GitHub according to [its quite limited ToS](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#5-license-grant-to-other-users).

Is this an intentional decision, or is it possible to add an open source license [of your choice](https://choosealicense.com/)? @vitalibo would have to agree to that in any case if this plugin shall be made open source, plus @fbezdeka and @ciarancourtney to make it possible to merge changes from their forks under that license.

**Comment by vitalibo** [comment]
I added Apache 2.0 license and I have no objections if you have the desire and ability to extend and publish this plugin, you can do that.

**Comment by fbezdeka** [comment]
I'm using the plugin with CLion 2022.1.3, all necessary adjustments can be found in my clone (2022.1 branch) https://github.com/fbezdeka/bitbake-intellij-plugin/commits/2022.1

All commits should have a Signed-off-by, but it's unclear to me where those changes should go to and as they have never been reviewed this should definitely be done.

@moqmar, where/how do you plan to maintain that? As @vitalibo is the official author he should at least be involved in reviews. Uploading/publishing in the Marketplace is a different thing (IMHO).

**Comment by moqmar** [comment]
Thank you, that's awesome! If @vitalibo wants to continue maintaining this project here that would be great, then I'd just create pull requests personally & you can also add me as a maintainer if you want me to e.g. review other pull requests.

If not, I can also try to get a fork at https://github.com/ZEISS approved, but it's preferred to keep changes upstream at the original repository if possible.

**Comment by vitalibo** [comment]
@moqmar at your choice. I don't have time to maintain the project right now, sent you an invitation.

**Comment by moqmar** [comment]
Thank you very much, I'll maintain it here then for now. 😃
