### ISSUE TITLE
Not working on CLion

### ISSUE THREAD

**Issue by ghost** [vitalibo/bitbake-intellij-plugin#9]
After installation, the plugin does not work on the CLion IDE. It does not apply code highlighting to any .bb nor .bbappend files.

**Comment by fbezdeka** [comment]
Maybe the same as in #2 ? I'm using the plugin in CLion, works but I had to configure a python interpreter first.

**Comment by fbezdeka** [comment]
Closing, no update for a long time and I'm using the plugin in CLion nearly each day. Works.
